In [194]:
import polars as pl

In [195]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/cases_2018.csv").head(5).collect()

shape: (5, 19)
┌────────────┬──────┬────────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ ddl_case_i ┆ year ┆ state_code ┆ dist_code ┆ … ┆ date_of_de ┆ date_first ┆ date_last ┆ date_next │
│ d          ┆ ---  ┆ ---        ┆ ---       ┆   ┆ cision     ┆ _list      ┆ _list     ┆ _list     │
│ ---        ┆ i64  ┆ i64        ┆ i64       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ str        ┆      ┆            ┆           ┆   ┆ str        ┆ str        ┆ str       ┆ str       │
╞════════════╪══════╪════════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-02-07 ┆ 2018-01-01 ┆ 2018-02-0 ┆ 2018-02-0 │
│ 0190000001 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 7         ┆ 7         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-02-01 ┆ 2018-01-01 ┆ 2018-02-0 ┆ 2018-02-0 │
│ 0190000002 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆ 1         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-02-01 ┆ 2018-01-01 ┆ 2018-02-0 ┆ 2018-02-0 │
│ 0190000003 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆ 1         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-02-01 ┆ 2018-01-01 ┆ 2018-02-0 ┆ 2018-02-0 │
│ 0190000004 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆ 1         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-01-09 ┆ 2018-01-01 ┆ 2018-01-0 ┆ 2018-01-0 │
│ 0190000005 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 9         ┆ 9         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
└────────────┴──────┴────────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [196]:
scan = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/cases_2018.csv")
scan.collect_schema()

Schema([('ddl_case_id', String),
        ('year', Int64),
        ('state_code', Int64),
        ('dist_code', Int64),
        ('court_no', Int64),
        ('cino', String),
        ('judge_position', String),
        ('female_defendant', String),
        ('female_petitioner', String),
        ('female_adv_def', Int64),
        ('female_adv_pet', Int64),
        ('type_name', Int64),
        ('purpose_name', Int64),
        ('disp_name', Int64),
        ('date_of_filing', String),
        ('date_of_decision', String),
        ('date_first_list', String),
        ('date_last_list', String),
        ('date_next_list', String)])

In [197]:
print(len(scan.collect_schema().names()))

19

In [198]:
scan.select(pl.len()).collect()

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ u32      │
╞══════════╡
│ 13724299 │
└──────────┘

In [199]:
scan.select(pl.col("female_petitioner").value_counts()).collect()

shape: (4, 1)
┌──────────────────────────────┐
│ female_petitioner            │
│ ---                          │
│ struct[2]                    │
╞══════════════════════════════╡
│ {"1 female",1877482}         │
│ {"-9998 unclear",7149001}    │
│ {"0 male",4621349}           │
│ {"-9999 missing name",76467} │
└──────────────────────────────┘

In [200]:
scan.select(pl.col("female_defendant").value_counts()).collect()

shape: (4, 1)
┌──────────────────────────────┐
│ female_defendant             │
│ ---                          │
│ struct[2]                    │
╞══════════════════════════════╡
│ {"0 male",9069681}           │
│ {"-9998 unclear",3058987}    │
│ {"-9999 missing name",92270} │
│ {"1 female",1503361}         │
└──────────────────────────────┘

In [201]:
scan.select(pl.col("female_petitioner").value_counts(sort=True)).unnest("female_petitioner").collect()

shape: (4, 2)
┌────────────────────┬─────────┐
│ female_petitioner  ┆ count   │
│ ---                ┆ ---     │
│ str                ┆ u32     │
╞════════════════════╪═════════╡
│ -9998 unclear      ┆ 7149001 │
│ 0 male             ┆ 4621349 │
│ 1 female           ┆ 1877482 │
│ -9999 missing name ┆ 76467   │
└────────────────────┴─────────┘

In [202]:
scan.select(pl.col("female_defendant").value_counts(sort=True)).unnest("female_defendant").collect()

shape: (4, 2)
┌────────────────────┬─────────┐
│ female_defendant   ┆ count   │
│ ---                ┆ ---     │
│ str                ┆ u32     │
╞════════════════════╪═════════╡
│ 0 male             ┆ 9069681 │
│ -9998 unclear      ┆ 3058987 │
│ 1 female           ┆ 1503361 │
│ -9999 missing name ┆ 92270   │
└────────────────────┴─────────┘

In [203]:
scan = scan.with_columns(pl.col(["date_of_filing", "date_of_decision", "date_first_list", "date_last_list", "date_next_list"]).str.to_date(format="%Y-%m-%d", strict=False))

In [204]:
scan.collect_schema()

Schema([('ddl_case_id', String),
        ('year', Int64),
        ('state_code', Int64),
        ('dist_code', Int64),
        ('court_no', Int64),
        ('cino', String),
        ('judge_position', String),
        ('female_defendant', String),
        ('female_petitioner', String),
        ('female_adv_def', Int64),
        ('female_adv_pet', Int64),
        ('type_name', Int64),
        ('purpose_name', Int64),
        ('disp_name', Int64),
        ('date_of_filing', Date),
        ('date_of_decision', Date),
        ('date_first_list', Date),
        ('date_last_list', Date),
        ('date_next_list', Date)])

In [205]:
scan.select(pl.col("female_adv_def").value_counts(sort=True)).unnest("female_adv_def").collect()

shape: (4, 2)
┌────────────────┬──────────┐
│ female_adv_def ┆ count    │
│ ---            ┆ ---      │
│ i64            ┆ u32      │
╞════════════════╪══════════╡
│ -9999          ┆ 12462880 │
│ 0              ┆ 1025979  │
│ -9998          ┆ 159906   │
│ 1              ┆ 75534    │
└────────────────┴──────────┘

In [206]:
scan.select(pl.col("female_adv_pet").value_counts(sort=True)).unnest("female_adv_pet").collect()

shape: (4, 2)
┌────────────────┬─────────┐
│ female_adv_pet ┆ count   │
│ ---            ┆ ---     │
│ i64            ┆ u32     │
╞════════════════╪═════════╡
│ 0              ┆ 6273261 │
│ -9999          ┆ 4115608 │
│ -9998          ┆ 2199904 │
│ 1              ┆ 1135526 │
└────────────────┴─────────┘

In [207]:
scan.null_count().collect()

shape: (1, 19)
┌────────────┬──────┬────────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ ddl_case_i ┆ year ┆ state_code ┆ dist_code ┆ … ┆ date_of_de ┆ date_first ┆ date_last ┆ date_next │
│ d          ┆ ---  ┆ ---        ┆ ---       ┆   ┆ cision     ┆ _list      ┆ _list     ┆ _list     │
│ ---        ┆ u32  ┆ u32        ┆ u32       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ u32        ┆      ┆            ┆           ┆   ┆ u32        ┆ u32        ┆ u32       ┆ u32       │
╞════════════╪══════╪════════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 0          ┆ 0    ┆ 0          ┆ 0         ┆ … ┆ 6327528    ┆ 585792     ┆ 53641     ┆ 501828    │
└────────────┴──────┴────────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [208]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/type_name_key.csv").head(5).collect()

shape: (5, 4)
┌──────┬───────────┬────────────────────┬───────┐
│ year ┆ type_name ┆ type_name_s        ┆ count │
│ ---  ┆ ---       ┆ ---                ┆ ---   │
│ i64  ┆ i64       ┆ str                ┆ i64   │
╞══════╪═══════════╪════════════════════╪═══════╡
│ 2010 ┆ 1         ┆ (m) t.s.           ┆ 18    │
│ 2010 ┆ 2         ┆ (sc)               ┆ 2     │
│ 2010 ┆ 3         ┆ ..mact 166         ┆ 97    │
│ 2010 ┆ 4         ┆ 04 complaint cases ┆ 19    │
│ 2010 ┆ 5         ┆ 04 criminal case   ┆ 21    │
└──────┴───────────┴────────────────────┴───────┘

In [209]:
type_key = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/type_name_key.csv").select(pl.col(["year", "type_name", "type_name_s"]))

In [210]:
type_key.collect_schema()

Schema([('year', Int64), ('type_name', Int64), ('type_name_s', String)])

In [211]:
cases_labeled = scan.join(type_key, on=["year", "type_name"], how="left")

In [212]:
cases_labeled.select(pl.len()).collect()

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ u32      │
╞══════════╡
│ 13724299 │
└──────────┘

In [213]:
cases_labeled.head(5).collect()

shape: (5, 20)
┌────────────┬──────┬────────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ ddl_case_i ┆ year ┆ state_code ┆ dist_code ┆ … ┆ date_first ┆ date_last_ ┆ date_next ┆ type_name │
│ d          ┆ ---  ┆ ---        ┆ ---       ┆   ┆ _list      ┆ list       ┆ _list     ┆ _s        │
│ ---        ┆ i64  ┆ i64        ┆ i64       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ str        ┆      ┆            ┆           ┆   ┆ date       ┆ date       ┆ date      ┆ str       │
╞════════════╪══════╪════════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-01-01 ┆ 2018-02-07 ┆ 2018-02-0 ┆ cri.m.a.  │
│ 0190000001 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 7         ┆           │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-01-01 ┆ 2018-02-01 ┆ 2018-02-0 ┆ cri.m.a.  │
│ 0190000002 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆           │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-01-01 ┆ 2018-02-01 ┆ 2018-02-0 ┆ cri.m.a.  │
│ 0190000003 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆           │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-01-01 ┆ 2018-02-01 ┆ 2018-02-0 ┆ cri.m.a.  │
│ 0190000004 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆           │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-01-01 ┆ 2018-01-09 ┆ 2018-01-0 ┆ cri.m.a.  │
│ 0190000005 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 9         ┆           │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
└────────────┴──────┴────────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [214]:
cases_labeled.select(pl.col("type_name_s").null_count()).collect()

shape: (1, 1)
┌─────────────┐
│ type_name_s │
│ ---         │
│ u32         │
╞═════════════╡
│ 0           │
└─────────────┘

In [215]:
disp_key = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/disp_name_key.csv").select(pl.col(["year", "disp_name", "disp_name_s"]))
purpose_key = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/purpose_name_key.csv").select(pl.col(["year", "purpose_name", "purpose_name_s"]))

In [216]:
cases_labeled = cases_labeled.join(disp_key, on=["year", "disp_name"], how="left")
cases_labeled = cases_labeled.join(purpose_key, on=["year", "purpose_name"], how="left")

In [217]:
cases_labeled.select(pl.len()).collect()

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ u32      │
╞══════════╡
│ 13724299 │
└──────────┘

In [218]:
cases_labeled.select(pl.col(["disp_name_s", "purpose_name_s"]).null_count()).collect()

shape: (1, 2)
┌─────────────┬────────────────┐
│ disp_name_s ┆ purpose_name_s │
│ ---         ┆ ---            │
│ u32         ┆ u32            │
╞═════════════╪════════════════╡
│ 0           ┆ 534098         │
└─────────────┴────────────────┘

In [219]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/cases_state_key.csv").collect_schema()

Schema([('year', Int64),
        ('state_code', Int64),
        ('state_name', String),
        ('pc11_state_name', String),
        ('pc11_state_id', Int64)])

In [220]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/cases_district_key.csv").collect_schema()

Schema([('year', Int64),
        ('state_code', Int64),
        ('state_name', String),
        ('dist_code', Int64),
        ('district_name', String),
        ('pc11_state_name', String),
        ('pc11_state_id', Int64),
        ('pc11_district_name', String),
        ('pc11_district_id', String)])

In [221]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/cases_court_key.csv").collect_schema()

Schema([('year', Int64),
        ('state_code', Int64),
        ('state_name', String),
        ('district_name', String),
        ('dist_code', Int64),
        ('court_no', Int64),
        ('court_name', String)])

In [222]:
cases_court = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/cases_court_key.csv")

In [223]:
cases_labeled = cases_labeled.join(cases_court, on=["year", "state_code", "dist_code", "court_no"], how="left")

In [224]:
cases_labeled.select(pl.len()).collect()

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ u32      │
╞══════════╡
│ 13724299 │
└──────────┘

In [225]:
cases_labeled.select(pl.col(["state_code", "dist_code", "court_no"]).null_count()).collect()

shape: (1, 3)
┌────────────┬───────────┬──────────┐
│ state_code ┆ dist_code ┆ court_no │
│ ---        ┆ ---       ┆ ---      │
│ u32        ┆ u32       ┆ u32      │
╞════════════╪═══════════╪══════════╡
│ 0          ┆ 0         ┆ 0        │
└────────────┴───────────┴──────────┘

In [226]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/judges_clean.csv").collect_schema()

Schema([('ddl_judge_id', Int64),
        ('state_code', Int64),
        ('dist_code', Int64),
        ('court_no', Int64),
        ('judge_position', String),
        ('female_judge', String),
        ('start_date', String),
        ('end_date', String)])

In [227]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/judge_case_merge_key.csv").collect_schema()

Schema([('ddl_case_id', String),
        ('ddl_filing_judge_id', Int64),
        ('ddl_decision_judge_id', Int64)])

In [228]:
judges_merge = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/judge_case_merge_key.csv")
judges_clean = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/judges_clean.csv")

judges_clean = judges_clean.with_columns(pl.col(["start_date", "end_date"]).str.to_date(format="%Y-%m-%d", strict=False))

filing_judges_clean = judges_clean.select(pl.col(['ddl_judge_id', 'female_judge', 'start_date', 'end_date']).name.suffix("_filing"))
decision_judges_clean = judges_clean.select(pl.col(['ddl_judge_id', 'female_judge', 'start_date', 'end_date']).name.suffix("_decision"))

In [229]:
cases_labeled = cases_labeled.join(judges_merge, on="ddl_case_id", how="left")

cases_labeled = cases_labeled.join(filing_judges_clean, left_on="ddl_filing_judge_id", right_on="ddl_judge_id_filing", how="left")
cases_labeled = cases_labeled.join(decision_judges_clean, left_on="ddl_decision_judge_id", right_on="ddl_judge_id_decision", how="left")

In [230]:
cases_labeled.collect_schema()

Schema([('ddl_case_id', String),
        ('year', Int64),
        ('state_code', Int64),
        ('dist_code', Int64),
        ('court_no', Int64),
        ('cino', String),
        ('judge_position', String),
        ('female_defendant', String),
        ('female_petitioner', String),
        ('female_adv_def', Int64),
        ('female_adv_pet', Int64),
        ('type_name', Int64),
        ('purpose_name', Int64),
        ('disp_name', Int64),
        ('date_of_filing', Date),
        ('date_of_decision', Date),
        ('date_first_list', Date),
        ('date_last_list', Date),
        ('date_next_list', Date),
        ('type_name_s', String),
        ('disp_name_s', String),
        ('purpose_name_s', String),
        ('state_name', String),
        ('district_name', String),
        ('court_name', String),
        ('ddl_filing_judge_id', Int64),
        ('ddl_decision_judge_id', Int64),
        ('female_judge_filing', String),
        ('start_date_filing', Date),
        ('end_date_filing', Date),
        ('female_judge_decision', String),
        ('start_date_decision', Date),
        ('end_date_decision', Date)])

In [231]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/act_key.csv").collect_schema()

Schema([('act_s', String), ('count', Int64), ('act', Int64)])

In [232]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/section_key.csv").collect_schema()

Schema([('section_s', String), ('count', Int64), ('section', Int64)])

In [233]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/acts_sections.csv").collect_schema()

Schema([('ddl_case_id', String),
        ('act', Int64),
        ('section', String),
        ('bailable_ipc', String),
        ('number_sections_ipc', Int64),
        ('criminal', Int64)])

In [234]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/acts_sections.csv").head(10).collect()

shape: (10, 6)
┌──────────────────────────┬───────┬─────────┬──────────────┬─────────────────────┬──────────┐
│ ddl_case_id              ┆ act   ┆ section ┆ bailable_ipc ┆ number_sections_ipc ┆ criminal │
│ ---                      ┆ ---   ┆ ---     ┆ ---          ┆ ---                 ┆ ---      │
│ str                      ┆ i64   ┆ str     ┆ str          ┆ i64                 ┆ i64      │
╞══════════════════════════╪═══════╪═════════╪══════════════╪═════════════════════╪══════════╡
│ 06-03-02-210100004042014 ┆ 17353 ┆ null    ┆ null         ┆ 1                   ┆ 1        │
│ 23-34-01-229900001012019 ┆ 4759  ┆ null    ┆ null         ┆ null                ┆ 1        │
│ 13-18-03-204000030972016 ┆ 17353 ┆ null    ┆ null         ┆ 1                   ┆ 1        │
│ 23-28-01-220102000232016 ┆ 4759  ┆ null    ┆ null         ┆ null                ┆ 1        │
│ 01-35-05-203007002652012 ┆ 17353 ┆ null    ┆ null         ┆ 1                   ┆ 1        │
│ 11-07-05-217800001262020 ┆ 4759  ┆ null    ┆ null         ┆ null                ┆ 1        │
│ 03-20-02-201200220682017 ┆ 4759  ┆ null    ┆ null         ┆ null                ┆ 1        │
│ 16-09-07-201600062352015 ┆ 17353 ┆ null    ┆ null         ┆ 1                   ┆ 1        │
│ 04-10-01-202301001952013 ┆ 17353 ┆ null    ┆ null         ┆ 1                   ┆ 1        │
│ 08-11-01-215200008432018 ┆ 17353 ┆ null    ┆ null         ┆ 1                   ┆ 1        │
└──────────────────────────┴───────┴─────────┴──────────────┴─────────────────────┴──────────┘

In [235]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/acts_sections.csv").select(pl.col("section").value_counts(sort=True)).unnest("section").collect()

shape: (2_113_919, 2)
┌─────────┬─────────┐
│ section ┆ count   │
│ ---     ┆ ---     │
│ str     ┆ u32     │
╞═════════╪═════════╡
│ null    ┆ 4834909 │
│ 213800  ┆ 3939583 │
│ 1182576 ┆ 2315311 │
│ 647330  ┆ 1527325 │
│ 965693  ┆ 1485923 │
│ …       ┆ …       │
│ 2113913 ┆ 1       │
│ 2113914 ┆ 1       │
│ 2113915 ┆ 1       │
│ 2113916 ┆ 1       │
│ 2113917 ┆ 1       │
└─────────┴─────────┘

In [236]:
act_key = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/act_key.csv")
section_key = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/section_key.csv")
acts_sections = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/acts_sections.csv")

In [237]:
act_key = act_key.select(pl.col(["act", "act_s"]))
section_key = section_key.select(pl.col(["section", "section_s"]))

In [238]:
acts_sections = acts_sections.with_columns(pl.col("section").cast(pl.Int64, strict=False))

In [239]:
acts_sections = acts_sections.join(cases_labeled.select("ddl_case_id"), on="ddl_case_id", how="semi")

acts_sections = acts_sections.join(act_key, on="act", how="left")

acts_sections = acts_sections.join(section_key, on="section", how="left")

In [242]:
acts_sections.sink_parquet("../ddl_judicial_data/ddl_judicial_data_2018_processed/acts_sections.parquet")

In [243]:
acts_sections.group_by("ddl_case_id").agg(pl.col("bailable_ipc").n_unique()).sort("bailable_ipc", descending=True).collect()

shape: (12_918_653, 2)
┌──────────────────────────┬──────────────┐
│ ddl_case_id              ┆ bailable_ipc │
│ ---                      ┆ ---          │
│ str                      ┆ u32          │
╞══════════════════════════╪══════════════╡
│ 13-02-03-206000006452018 ┆ 1            │
│ 14-02-05-204700000162018 ┆ 1            │
│ 23-01-01-220400002402018 ┆ 1            │
│ 13-67-07-205700002172018 ┆ 1            │
│ 01-01-10-201900004672018 ┆ 1            │
│ …                        ┆ …            │
│ 26-03-01-203800008782018 ┆ 1            │
│ 13-31-05-206100016662018 ┆ 1            │
│ 02-04-18-202100002612018 ┆ 1            │
│ 13-12-03-208200178232018 ┆ 1            │
│ 01-25-27-203000000362018 ┆ 1            │
└──────────────────────────┴──────────────┘

In [ ]:
acts_sections.group_by("ddl_case_id").agg(pl.col("criminal").n_unique()).sort("criminal", descending=True).collect()

shape: (12_918_653, 2)
┌──────────────────────────┬──────────┐
│ ddl_case_id              ┆ criminal │
│ ---                      ┆ ---      │
│ str                      ┆ u32      │
╞══════════════════════════╪══════════╡
│ 14-06-04-200400000042018 ┆ 1        │
│ 16-20-07-206400000232018 ┆ 1        │
│ 18-06-10-206900008912018 ┆ 1        │
│ 11-10-10-204700002882018 ┆ 1        │
│ 09-08-18-253100009112018 ┆ 1        │
│ …                        ┆ …        │
│ 26-11-02-202100012692018 ┆ 1        │
│ 04-15-19-204601021112018 ┆ 1        │
│ 01-28-04-203400005292018 ┆ 1        │
│ 11-17-03-205100000232018 ┆ 1        │
│ 09-18-03-253300003522018 ┆ 1        │
└──────────────────────────┴──────────┘

In [ ]:
acts_sections.group_by("ddl_case_id").agg(pl.col("number_sections_ipc").n_unique()).sort("number_sections_ipc", descending=True).collect()

shape: (12_918_653, 2)
┌──────────────────────────┬─────────────────────┐
│ ddl_case_id              ┆ number_sections_ipc │
│ ---                      ┆ ---                 │
│ str                      ┆ u32                 │
╞══════════════════════════╪═════════════════════╡
│ 16-11-13-205600009082018 ┆ 1                   │
│ 23-13-02-220600002082018 ┆ 1                   │
│ 09-02-45-253300002342018 ┆ 1                   │
│ 17-25-05-205900001952018 ┆ 1                   │
│ 08-31-01-201000002892018 ┆ 1                   │
│ …                        ┆ …                   │
│ 22-17-02-201500000122018 ┆ 1                   │
│ 09-04-24-253300022162018 ┆ 1                   │
│ 03-27-01-204700000282018 ┆ 1                   │
│ 29-01-18-201700001042018 ┆ 1                   │
│ 13-42-02-202012003212010 ┆ 1                   │
└──────────────────────────┴─────────────────────┘

In [244]:
acts_by_case = acts_sections.group_by("ddl_case_id").agg(pl.col(["act_s", "section_s"]), pl.col(["number_sections_ipc", "criminal", "bailable_ipc"]).drop_nulls().first(), pl.len().alias("n_acts_or_sections"))

In [245]:
cases_labeled = cases_labeled.join(acts_by_case, on="ddl_case_id", how="left")

cases_labeled.select(pl.col(["act_s", "section_s", "number_sections_ipc", "criminal", "bailable_ipc", "n_acts_or_sections"]).null_count()).collect()

shape: (1, 6)
┌────────┬───────────┬─────────────────────┬──────────┬──────────────┬────────────────────┐
│ act_s  ┆ section_s ┆ number_sections_ipc ┆ criminal ┆ bailable_ipc ┆ n_acts_or_sections │
│ ---    ┆ ---       ┆ ---                 ┆ ---      ┆ ---          ┆ ---                │
│ u32    ┆ u32       ┆ u32                 ┆ u32      ┆ u32          ┆ u32                │
╞════════╪═══════════╪═════════════════════╪══════════╪══════════════╪════════════════════╡
│ 805646 ┆ 805646    ┆ 10260463            ┆ 805646   ┆ 10364741     ┆ 805646             │
└────────┴───────────┴─────────────────────┴──────────┴──────────────┴────────────────────┘

In [246]:
cases_labeled.select(pl.len()).collect()

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ u32      │
╞══════════╡
│ 13724299 │
└──────────┘

In [247]:
cases_labeled.sink_parquet("../ddl_judicial_data/ddl_judicial_data_2018_processed/cases_labeled.parquet")