In [94]:
import polars as pl

In [95]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/cases_2018.csv").head(5).collect()

shape: (5, 19)
┌────────────┬──────┬────────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ ddl_case_i ┆ year ┆ state_code ┆ dist_code ┆ … ┆ date_of_de ┆ date_first ┆ date_last ┆ date_next │
│ d          ┆ ---  ┆ ---        ┆ ---       ┆   ┆ cision     ┆ _list      ┆ _list     ┆ _list     │
│ ---        ┆ i64  ┆ i64        ┆ i64       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ str        ┆      ┆            ┆           ┆   ┆ str        ┆ str        ┆ str       ┆ str       │
╞════════════╪══════╪════════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-02-07 ┆ 2018-01-01 ┆ 2018-02-0 ┆ 2018-02-0 │
│ 0190000001 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 7         ┆ 7         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-02-01 ┆ 2018-01-01 ┆ 2018-02-0 ┆ 2018-02-0 │
│ 0190000002 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆ 1         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-02-01 ┆ 2018-01-01 ┆ 2018-02-0 ┆ 2018-02-0 │
│ 0190000003 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆ 1         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-02-01 ┆ 2018-01-01 ┆ 2018-02-0 ┆ 2018-02-0 │
│ 0190000004 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆ 1         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-01-09 ┆ 2018-01-01 ┆ 2018-01-0 ┆ 2018-01-0 │
│ 0190000005 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 9         ┆ 9         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
└────────────┴──────┴────────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [96]:
scan = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/cases_2018.csv")
scan.collect_schema()

Schema([('ddl_case_id', String),
        ('year', Int64),
        ('state_code', Int64),
        ('dist_code', Int64),
        ('court_no', Int64),
        ('cino', String),
        ('judge_position', String),
        ('female_defendant', String),
        ('female_petitioner', String),
        ('female_adv_def', Int64),
        ('female_adv_pet', Int64),
        ('type_name', Int64),
        ('purpose_name', Int64),
        ('disp_name', Int64),
        ('date_of_filing', String),
        ('date_of_decision', String),
        ('date_first_list', String),
        ('date_last_list', String),
        ('date_next_list', String)])

In [97]:
print(len(scan.collect_schema().names()))

19

In [98]:
scan.select(pl.len()).collect()

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ u32      │
╞══════════╡
│ 13724299 │
└──────────┘

In [99]:
scan.select(pl.col("female_petitioner").value_counts()).collect()

shape: (4, 1)
┌──────────────────────────────┐
│ female_petitioner            │
│ ---                          │
│ struct[2]                    │
╞══════════════════════════════╡
│ {"-9998 unclear",7149001}    │
│ {"-9999 missing name",76467} │
│ {"0 male",4621349}           │
│ {"1 female",1877482}         │
└──────────────────────────────┘

In [100]:
scan.select(pl.col("female_defendant").value_counts()).collect()

shape: (4, 1)
┌──────────────────────────────┐
│ female_defendant             │
│ ---                          │
│ struct[2]                    │
╞══════════════════════════════╡
│ {"0 male",9069681}           │
│ {"1 female",1503361}         │
│ {"-9999 missing name",92270} │
│ {"-9998 unclear",3058987}    │
└──────────────────────────────┘

In [101]:
scan.select(pl.col("female_petitioner").value_counts(sort=True)).unnest("female_petitioner").collect()

shape: (4, 2)
┌────────────────────┬─────────┐
│ female_petitioner  ┆ count   │
│ ---                ┆ ---     │
│ str                ┆ u32     │
╞════════════════════╪═════════╡
│ -9998 unclear      ┆ 7149001 │
│ 0 male             ┆ 4621349 │
│ 1 female           ┆ 1877482 │
│ -9999 missing name ┆ 76467   │
└────────────────────┴─────────┘

In [102]:
scan.select(pl.col("female_defendant").value_counts(sort=True)).unnest("female_defendant").collect()

shape: (4, 2)
┌────────────────────┬─────────┐
│ female_defendant   ┆ count   │
│ ---                ┆ ---     │
│ str                ┆ u32     │
╞════════════════════╪═════════╡
│ 0 male             ┆ 9069681 │
│ -9998 unclear      ┆ 3058987 │
│ 1 female           ┆ 1503361 │
│ -9999 missing name ┆ 92270   │
└────────────────────┴─────────┘

In [103]:
scan = scan.with_columns(pl.col(["date_of_filing", "date_of_decision", "date_first_list", "date_last_list", "date_next_list"]).str.to_date(format="%Y-%m-%d", strict=False))

In [104]:
scan.collect_schema()

Schema([('ddl_case_id', String),
        ('year', Int64),
        ('state_code', Int64),
        ('dist_code', Int64),
        ('court_no', Int64),
        ('cino', String),
        ('judge_position', String),
        ('female_defendant', String),
        ('female_petitioner', String),
        ('female_adv_def', Int64),
        ('female_adv_pet', Int64),
        ('type_name', Int64),
        ('purpose_name', Int64),
        ('disp_name', Int64),
        ('date_of_filing', Date),
        ('date_of_decision', Date),
        ('date_first_list', Date),
        ('date_last_list', Date),
        ('date_next_list', Date)])

In [105]:
scan.select(pl.col("female_adv_def").value_counts(sort=True)).unnest("female_adv_def").collect()

shape: (4, 2)
┌────────────────┬──────────┐
│ female_adv_def ┆ count    │
│ ---            ┆ ---      │
│ i64            ┆ u32      │
╞════════════════╪══════════╡
│ -9999          ┆ 12462880 │
│ 0              ┆ 1025979  │
│ -9998          ┆ 159906   │
│ 1              ┆ 75534    │
└────────────────┴──────────┘

In [106]:
scan.select(pl.col("female_adv_pet").value_counts(sort=True)).unnest("female_adv_pet").collect()

shape: (4, 2)
┌────────────────┬─────────┐
│ female_adv_pet ┆ count   │
│ ---            ┆ ---     │
│ i64            ┆ u32     │
╞════════════════╪═════════╡
│ 0              ┆ 6273261 │
│ -9999          ┆ 4115608 │
│ -9998          ┆ 2199904 │
│ 1              ┆ 1135526 │
└────────────────┴─────────┘

In [107]:
scan.null_count().collect()

shape: (1, 19)
┌────────────┬──────┬────────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ ddl_case_i ┆ year ┆ state_code ┆ dist_code ┆ … ┆ date_of_de ┆ date_first ┆ date_last ┆ date_next │
│ d          ┆ ---  ┆ ---        ┆ ---       ┆   ┆ cision     ┆ _list      ┆ _list     ┆ _list     │
│ ---        ┆ u32  ┆ u32        ┆ u32       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ u32        ┆      ┆            ┆           ┆   ┆ u32        ┆ u32        ┆ u32       ┆ u32       │
╞════════════╪══════╪════════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 0          ┆ 0    ┆ 0          ┆ 0         ┆ … ┆ 6327528    ┆ 585792     ┆ 53641     ┆ 501828    │
└────────────┴──────┴────────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [108]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/type_name_key.csv").head(5).collect()

shape: (5, 4)
┌──────┬───────────┬────────────────────┬───────┐
│ year ┆ type_name ┆ type_name_s        ┆ count │
│ ---  ┆ ---       ┆ ---                ┆ ---   │
│ i64  ┆ i64       ┆ str                ┆ i64   │
╞══════╪═══════════╪════════════════════╪═══════╡
│ 2010 ┆ 1         ┆ (m) t.s.           ┆ 18    │
│ 2010 ┆ 2         ┆ (sc)               ┆ 2     │
│ 2010 ┆ 3         ┆ ..mact 166         ┆ 97    │
│ 2010 ┆ 4         ┆ 04 complaint cases ┆ 19    │
│ 2010 ┆ 5         ┆ 04 criminal case   ┆ 21    │
└──────┴───────────┴────────────────────┴───────┘

In [109]:
type_key = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/type_name_key.csv").select(pl.col(["year", "type_name", "type_name_s"]))

In [110]:
type_key.collect_schema()

Schema([('year', Int64), ('type_name', Int64), ('type_name_s', String)])

In [111]:
cases_labeled = scan.join(type_key, on=["year", "type_name"], how="left")

In [112]:
cases_labeled.select(pl.len()).collect()

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ u32      │
╞══════════╡
│ 13724299 │
└──────────┘

In [113]:
cases_labeled.head(5).collect()

shape: (5, 20)
┌────────────┬──────┬────────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ ddl_case_i ┆ year ┆ state_code ┆ dist_code ┆ … ┆ date_first ┆ date_last_ ┆ date_next ┆ type_name │
│ d          ┆ ---  ┆ ---        ┆ ---       ┆   ┆ _list      ┆ list       ┆ _list     ┆ _s        │
│ ---        ┆ i64  ┆ i64        ┆ i64       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ str        ┆      ┆            ┆           ┆   ┆ date       ┆ date       ┆ date      ┆ str       │
╞════════════╪══════╪════════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-01-01 ┆ 2018-02-07 ┆ 2018-02-0 ┆ cri.m.a.  │
│ 0190000001 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 7         ┆           │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-01-01 ┆ 2018-02-01 ┆ 2018-02-0 ┆ cri.m.a.  │
│ 0190000002 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆           │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-01-01 ┆ 2018-02-01 ┆ 2018-02-0 ┆ cri.m.a.  │
│ 0190000003 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆           │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-01-01 ┆ 2018-02-01 ┆ 2018-02-0 ┆ cri.m.a.  │
│ 0190000004 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆           │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-01-01 ┆ 2018-01-09 ┆ 2018-01-0 ┆ cri.m.a.  │
│ 0190000005 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 9         ┆           │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
└────────────┴──────┴────────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [114]:
cases_labeled.select(pl.col("type_name_s").null_count()).collect()

shape: (1, 1)
┌─────────────┐
│ type_name_s │
│ ---         │
│ u32         │
╞═════════════╡
│ 0           │
└─────────────┘

In [115]:
disp_key = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/disp_name_key.csv").select(pl.col(["year", "disp_name", "disp_name_s"]))
purpose_key = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/purpose_name_key.csv").select(pl.col(["year", "purpose_name", "purpose_name_s"]))

In [116]:
cases_labeled = cases_labeled.join(disp_key, on=["year", "disp_name"], how="left")
cases_labeled = cases_labeled.join(purpose_key, on=["year", "purpose_name"], how="left")

In [117]:
cases_labeled.select(pl.len()).collect()

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ u32      │
╞══════════╡
│ 13724299 │
└──────────┘

In [118]:
cases_labeled.select(pl.col(["disp_name_s", "purpose_name_s"]).null_count()).collect()

shape: (1, 2)
┌─────────────┬────────────────┐
│ disp_name_s ┆ purpose_name_s │
│ ---         ┆ ---            │
│ u32         ┆ u32            │
╞═════════════╪════════════════╡
│ 0           ┆ 534098         │
└─────────────┴────────────────┘

In [119]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/cases_state_key.csv").collect_schema()

Schema([('year', Int64),
        ('state_code', Int64),
        ('state_name', String),
        ('pc11_state_name', String),
        ('pc11_state_id', Int64)])

In [120]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/cases_district_key.csv").collect_schema()

Schema([('year', Int64),
        ('state_code', Int64),
        ('state_name', String),
        ('dist_code', Int64),
        ('district_name', String),
        ('pc11_state_name', String),
        ('pc11_state_id', Int64),
        ('pc11_district_name', String),
        ('pc11_district_id', String)])

In [121]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/cases_court_key.csv").collect_schema()

Schema([('year', Int64),
        ('state_code', Int64),
        ('state_name', String),
        ('district_name', String),
        ('dist_code', Int64),
        ('court_no', Int64),
        ('court_name', String)])

In [122]:
cases_court = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/cases_court_key.csv")

In [123]:
cases_labeled = cases_labeled.join(cases_court, on=["year", "state_code", "dist_code", "court_no"], how="left")

In [124]:
cases_labeled.select(pl.len()).collect()

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ u32      │
╞══════════╡
│ 13724299 │
└──────────┘

In [125]:
cases_labeled.select(pl.col(["state_code", "dist_code", "court_no"]).null_count()).collect()

shape: (1, 3)
┌────────────┬───────────┬──────────┐
│ state_code ┆ dist_code ┆ court_no │
│ ---        ┆ ---       ┆ ---      │
│ u32        ┆ u32       ┆ u32      │
╞════════════╪═══════════╪══════════╡
│ 0          ┆ 0         ┆ 0        │
└────────────┴───────────┴──────────┘

In [126]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/judges_clean.csv").collect_schema()

Schema([('ddl_judge_id', Int64),
        ('state_code', Int64),
        ('dist_code', Int64),
        ('court_no', Int64),
        ('judge_position', String),
        ('female_judge', String),
        ('start_date', String),
        ('end_date', String)])

In [127]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/judge_case_merge_key.csv").collect_schema()

Schema([('ddl_case_id', String),
        ('ddl_filing_judge_id', Int64),
        ('ddl_decision_judge_id', Int64)])

In [128]:
judges_merge = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/judge_case_merge_key.csv")
judges_clean = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/judges_clean.csv")

judges_clean = judges_clean.with_columns(pl.col(["start_date", "end_date"]).str.to_date(format="%Y-%m-%d", strict=False))

filing_judges_clean = judges_clean.select(pl.col(['ddl_judge_id', 'female_judge', 'start_date', 'end_date']).name.suffix("_filing"))
decision_judges_clean = judges_clean.select(pl.col(['ddl_judge_id', 'female_judge', 'start_date', 'end_date']).name.suffix("_decision"))

In [129]:
cases_labeled = cases_labeled.join(judges_merge, on="ddl_case_id", how="left")

cases_labeled = cases_labeled.join(filing_judges_clean, left_on="ddl_filing_judge_id", right_on="ddl_judge_id_filing", how="left")
cases_labeled = cases_labeled.join(decision_judges_clean, left_on="ddl_decision_judge_id", right_on="ddl_judge_id_decision", how="left")