In [61]:
import polars as pl

In [62]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/cases_2018.csv").head(5).collect()

shape: (5, 19)
┌────────────┬──────┬────────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ ddl_case_i ┆ year ┆ state_code ┆ dist_code ┆ … ┆ date_of_de ┆ date_first ┆ date_last ┆ date_next │
│ d          ┆ ---  ┆ ---        ┆ ---       ┆   ┆ cision     ┆ _list      ┆ _list     ┆ _list     │
│ ---        ┆ i64  ┆ i64        ┆ i64       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ str        ┆      ┆            ┆           ┆   ┆ str        ┆ str        ┆ str       ┆ str       │
╞════════════╪══════╪════════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-02-07 ┆ 2018-01-01 ┆ 2018-02-0 ┆ 2018-02-0 │
│ 0190000001 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 7         ┆ 7         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-02-01 ┆ 2018-01-01 ┆ 2018-02-0 ┆ 2018-02-0 │
│ 0190000002 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆ 1         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-02-01 ┆ 2018-01-01 ┆ 2018-02-0 ┆ 2018-02-0 │
│ 0190000003 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆ 1         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-02-01 ┆ 2018-01-01 ┆ 2018-02-0 ┆ 2018-02-0 │
│ 0190000004 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 1         ┆ 1         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
│ 01-01-01-2 ┆ 2018 ┆ 1          ┆ 1         ┆ … ┆ 2018-01-09 ┆ 2018-01-01 ┆ 2018-01-0 ┆ 2018-01-0 │
│ 0190000005 ┆      ┆            ┆           ┆   ┆            ┆            ┆ 9         ┆ 9         │
│ 2018       ┆      ┆            ┆           ┆   ┆            ┆            ┆           ┆           │
└────────────┴──────┴────────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [63]:
scan = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/cases_2018.csv")
scan.collect_schema()

Schema([('ddl_case_id', String),
        ('year', Int64),
        ('state_code', Int64),
        ('dist_code', Int64),
        ('court_no', Int64),
        ('cino', String),
        ('judge_position', String),
        ('female_defendant', String),
        ('female_petitioner', String),
        ('female_adv_def', Int64),
        ('female_adv_pet', Int64),
        ('type_name', Int64),
        ('purpose_name', Int64),
        ('disp_name', Int64),
        ('date_of_filing', String),
        ('date_of_decision', String),
        ('date_first_list', String),
        ('date_last_list', String),
        ('date_next_list', String)])

In [64]:
print(len(scan.collect_schema().names()))

19

In [65]:
scan.select(pl.len()).collect()

shape: (1, 1)
┌──────────┐
│ len      │
│ ---      │
│ u32      │
╞══════════╡
│ 13724299 │
└──────────┘

In [66]:
scan.select(pl.col("female_petitioner").value_counts()).collect()

shape: (4, 1)
┌──────────────────────────────┐
│ female_petitioner            │
│ ---                          │
│ struct[2]                    │
╞══════════════════════════════╡
│ {"0 male",4621349}           │
│ {"-9999 missing name",76467} │
│ {"1 female",1877482}         │
│ {"-9998 unclear",7149001}    │
└──────────────────────────────┘

In [67]:
scan.select(pl.col("female_defendant").value_counts()).collect()

shape: (4, 1)
┌──────────────────────────────┐
│ female_defendant             │
│ ---                          │
│ struct[2]                    │
╞══════════════════════════════╡
│ {"0 male",9069681}           │
│ {"-9999 missing name",92270} │
│ {"1 female",1503361}         │
│ {"-9998 unclear",3058987}    │
└──────────────────────────────┘

In [68]:
scan.select(pl.col("female_petitioner").value_counts(sort=True)).unnest("female_petitioner").collect()

shape: (4, 2)
┌────────────────────┬─────────┐
│ female_petitioner  ┆ count   │
│ ---                ┆ ---     │
│ str                ┆ u32     │
╞════════════════════╪═════════╡
│ -9998 unclear      ┆ 7149001 │
│ 0 male             ┆ 4621349 │
│ 1 female           ┆ 1877482 │
│ -9999 missing name ┆ 76467   │
└────────────────────┴─────────┘

In [69]:
scan.select(pl.col("female_defendant").value_counts(sort=True)).unnest("female_defendant").collect()

shape: (4, 2)
┌────────────────────┬─────────┐
│ female_defendant   ┆ count   │
│ ---                ┆ ---     │
│ str                ┆ u32     │
╞════════════════════╪═════════╡
│ 0 male             ┆ 9069681 │
│ -9998 unclear      ┆ 3058987 │
│ 1 female           ┆ 1503361 │
│ -9999 missing name ┆ 92270   │
└────────────────────┴─────────┘

In [70]:
scan = scan.with_columns(pl.col(["date_of_filing", "date_of_decision", "date_first_list", "date_last_list", "date_next_list"]).str.to_date(format="%Y-%m-%d", strict=False))

In [71]:
scan.collect_schema()

Schema([('ddl_case_id', String),
        ('year', Int64),
        ('state_code', Int64),
        ('dist_code', Int64),
        ('court_no', Int64),
        ('cino', String),
        ('judge_position', String),
        ('female_defendant', String),
        ('female_petitioner', String),
        ('female_adv_def', Int64),
        ('female_adv_pet', Int64),
        ('type_name', Int64),
        ('purpose_name', Int64),
        ('disp_name', Int64),
        ('date_of_filing', Date),
        ('date_of_decision', Date),
        ('date_first_list', Date),
        ('date_last_list', Date),
        ('date_next_list', Date)])

In [72]:
scan.select(pl.col("female_adv_def").value_counts(sort=True)).unnest("female_adv_def").collect()

shape: (4, 2)
┌────────────────┬──────────┐
│ female_adv_def ┆ count    │
│ ---            ┆ ---      │
│ i64            ┆ u32      │
╞════════════════╪══════════╡
│ -9999          ┆ 12462880 │
│ 0              ┆ 1025979  │
│ -9998          ┆ 159906   │
│ 1              ┆ 75534    │
└────────────────┴──────────┘

In [73]:
scan.select(pl.col("female_adv_pet").value_counts(sort=True)).unnest("female_adv_pet").collect()

shape: (4, 2)
┌────────────────┬─────────┐
│ female_adv_pet ┆ count   │
│ ---            ┆ ---     │
│ i64            ┆ u32     │
╞════════════════╪═════════╡
│ 0              ┆ 6273261 │
│ -9999          ┆ 4115608 │
│ -9998          ┆ 2199904 │
│ 1              ┆ 1135526 │
└────────────────┴─────────┘

In [74]:
scan.null_count().collect()

shape: (1, 19)
┌────────────┬──────┬────────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ ddl_case_i ┆ year ┆ state_code ┆ dist_code ┆ … ┆ date_of_de ┆ date_first ┆ date_last ┆ date_next │
│ d          ┆ ---  ┆ ---        ┆ ---       ┆   ┆ cision     ┆ _list      ┆ _list     ┆ _list     │
│ ---        ┆ u32  ┆ u32        ┆ u32       ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ u32        ┆      ┆            ┆           ┆   ┆ u32        ┆ u32        ┆ u32       ┆ u32       │
╞════════════╪══════╪════════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 0          ┆ 0    ┆ 0          ┆ 0         ┆ … ┆ 6327528    ┆ 585792     ┆ 53641     ┆ 501828    │
└────────────┴──────┴────────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [75]:
pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/type_name_key.csv").head(5).collect()

shape: (5, 4)
┌──────┬───────────┬────────────────────┬───────┐
│ year ┆ type_name ┆ type_name_s        ┆ count │
│ ---  ┆ ---       ┆ ---                ┆ ---   │
│ i64  ┆ i64       ┆ str                ┆ i64   │
╞══════╪═══════════╪════════════════════╪═══════╡
│ 2010 ┆ 1         ┆ (m) t.s.           ┆ 18    │
│ 2010 ┆ 2         ┆ (sc)               ┆ 2     │
│ 2010 ┆ 3         ┆ ..mact 166         ┆ 97    │
│ 2010 ┆ 4         ┆ 04 complaint cases ┆ 19    │
│ 2010 ┆ 5         ┆ 04 criminal case   ┆ 21    │
└──────┴───────────┴────────────────────┴───────┘

In [77]:
type_key = pl.scan_csv("../ddl_judicial_data/ddl_judicial_data_2018extracted/type_name_key.csv")
type_key.collect_schema()

Schema([('year', Int64),
        ('type_name', Int64),
        ('type_name_s', String),
        ('count', Int64)])